/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package togise.kotest.path.stackoverflow

import java.nio.file.Paths
import io.kotest.assertions.show.show
import io.kotest.matchers.shouldBe
import org.junit.jupiter.api.Test

class StackOverflowTest {
    @Test
    fun testSomeLibraryMethod() {
        println(Paths.get("a/b/c").show().value)
    }
}
